<?php
    session_start();
    require('../src/verifAdmin.php');
    require('../../src/Connect.php');
    require('../src/FormAddTueur.php');
    require('../../src/Disconnect.php');
    require('../templates/TempHeaderAdmin.php');
    require('../templates/TempAddTueur.php');
    require('../templates/TempFooter.php');
?>